# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tytu\u0142')),
                ('content', models.TextField(verbose_name='Zawarto\u015b\u0107')),
                ('published', models.DateTimeField(verbose_name='Data publikacji')),
            ],
        ),
    ]
