# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-05 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to='images/', verbose_name='Obraz'),
        ),
    ]
