# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-07 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20170505_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='U\u017cytkownik')),
                ('content', models.TextField(verbose_name='Komentarz')),
                ('published', models.DateTimeField(verbose_name='Data publikacji')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
        ),
    ]
