# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-05 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tytu\u0142')),
                ('sourcehtml', models.TextField(verbose_name='Kod html')),
            ],
        ),
    ]
